CREATE TABLE staff(
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    name VARCHAR(24) NOT NULL,
    address VARCHAR(1024),
    IC VARCHAR(14) NOT NULL, 
    PHONE_NUMBER VARCHAR(11), 
    USERNAME VARCHAR(20) NOT NULL, 
    PASSWORD VARCHAR(20) NOT NULL,
    CONSTRAINT staff_pk PRIMARY KEY (id)
) ;

CREATE TABLE TASK (
 id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
 name VARCHAR(3) NOT NULL,
 DESCRIPTION VARCHAR(50), PRIMARY KEY (ID);
 CONSTRAINT staff_pk PRIMARY KEY (id)
 );
